image: alpine/edge
packages:
  - deno
secrets:
  - 0323bc6f-a046-4b96-8496-2bac6e7ee107
  - 0f45fdd0-5af6-4cfb-bece-754aee60fdd6
environment:
  dir: wcarbon
triggers:
  - action: email
    condition: failure
    to: tim@harek.no
tasks:
  - test: |
      cd $dir
      deno task check
      deno task test
  - check: |
      cd $dir
      if [ "$(git rev-parse origin/main)" != "$(git rev-parse HEAD)" ]; then \
        complete-build; \
      fi
  - new_release: |
      set +x
      export JSR_API=$(cat ~/jsr_timharek)
      set -x
      deno publish --allow-slow-types --token $JSR_API
  - mirror: |
      cd $dir
      git remote add github git@github.com:timharek/wcarbon.git
      ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
      git push github main
      if [ "$(git describe --exact-match --tags HEAD)" ]; then \
        git push --tags github; \
      fi

